-- ============================================================
-- Builder Procurement Agents Creation
-- Generated by Nimbus - Supabase Database Specialist
-- Company: MeasureForge AI
-- Date: 2026-04-24
-- Purpose: Create 9 specialized procurement agents for builder workflows
-- ============================================================

-- Step 1: Get MeasureForge AI company ID
-- SELECT id, name FROM companies WHERE name LIKE '%MeasureForge%';

-- ============================================================
-- IMPORTANT: Schema constraints for this table:
-- - agents table has NO unique constraint on 'name'
-- - Model config is stored in adapter_config JSONB field
-- - API keys are stored in agent_api_keys table with SHA256 hashes
-- - Activity logs track all agent creation events
-- ============================================================

-- ============================================================
-- AGENT REGISTRATION (Idempotent - uses NOT EXISTS check)
-- ============================================================

-- 1. Sage Weaver - Procurement Classifier
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  runtime_config,
  adapter_config,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  c.id,
  'Sage Weaver',
  'specialist',
  'Procurement Classifier - Builder',
  '🧙',
  'active',
   (SELECT id FROM agents WHERE name = 'measureforge-ai-measurement-director' AND company_id = c.id),
  '["cad-measurement-interpretation", "procurement-classification-rules", "material-type-recognition", "trade-specialization-knowledge"]',
  'hermes_local',
  '{"run_heartbeat": 300}'::jsonb,
  '{
    "adapter": "hermes_local",
    "model": "anthropic/claude-opus-4.6",
    "temperature": 0.7,
    "max_tokens": 4096,
    "environment": {
      "OPENROUTER_API_KEY": "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"
    },
    "skills": ["cad-measurement-interpretation", "procurement-classification-rules", "material-type-recognition", "trade-specialization-knowledge"]
  }'::jsonb,
  NOW(),
  NOW()
FROM companies c
WHERE c.name = 'MeasureForge AI'
  AND NOT EXISTS (
    SELECT 1 FROM agents a
    WHERE a.name = 'Sage Weaver'
      AND a.company_id = c.id
  );

-- 2. Forge Master - Subcontract Procurement Agent
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  runtime_config,
  adapter_config,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  c.id,
  'Forge Master',
  'specialist',
  'Subcontract Procurement Agent - Builder',
  '🔨',
  'active',
  (SELECT id FROM agents WHERE name = 'measureforge-ai-procurement-director' AND company_id = c.id),
  '["trade-specification-interpretation", "subcontractor-evaluation", "rfq-document-generation", "compliance-scoring", "cidb-verification"]',
  'hermes_local',
  '{"run_heartbeat": 300}'::jsonb,
  '{
    "adapter": "hermes_local",
    "model": "anthropic/claude-opus-4.6",
    "temperature": 0.7,
    "max_tokens": 4096,
    "environment": {
      "OPENROUTER_API_KEY": "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"
    },
    "skills": ["trade-specification-interpretation", "subcontractor-evaluation", "rfq-document-generation", "compliance-scoring", "cidb-verification"]
  }'::jsonb,
  NOW(),
  NOW()
FROM companies c
WHERE c.name = 'MeasureForge AI'
  AND NOT EXISTS (
    SELECT 1 FROM agents a
    WHERE a.name = 'Forge Master'
      AND a.company_id = c.id
  );

-- 3. Resource Baron - Materials Procurement Agent
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  runtime_config,
  adapter_config,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  c.id,
  'Resource Baron',
  'specialist',
  'Materials Procurement Agent - Builder',
  '👑',
  'active',
  (SELECT id FROM agents WHERE name = 'measureforge-ai-procurement-director' AND company_id = c.id),
  '["material-specification-interpretation", "candy-system-integration", "bulk-ordering-optimization", "supplier-catalog-management"]',
  'hermes_local',
  '{"run_heartbeat": 300}'::jsonb,
  '{
    "adapter": "hermes_local",
    "model": "anthropic/claude-sonnet-4.5",
    "temperature": 0.7,
    "max_tokens": 4096,
    "environment": {
      "OPENROUTER_API_KEY": "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"
    },
    "skills": ["material-specification-interpretation", "candy-system-integration", "bulk-ordering-optimization", "supplier-catalog-management"]
  }'::jsonb,
  NOW(),
  NOW()
FROM companies c
WHERE c.name = 'MeasureForge AI'
  AND NOT EXISTS (
    SELECT 1 FROM agents a
    WHERE a.name = 'Resource Baron'
      AND a.company_id = c.id
  );

-- 4. Service Sage - Service Procurement Agent
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  runtime_config,
  adapter_config,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  c.id,
  'Service Sage',
  'specialist',
  'Service Procurement Agent - Builder',
  '🧠',
  'active',
  (SELECT id FROM agents WHERE name = 'measureforge-ai-procurement-director' AND company_id = c.id),
  '["service-requirement-analysis", "provider-certification-verification", "service-order-generation", "timeline-scheduling"]',
  'hermes_local',
  '{"run_heartbeat": 300}'::jsonb,
  '{
    "adapter": "hermes_local",
    "model": "anthropic/claude-sonnet-4.5",
    "temperature": 0.7,
    "max_tokens": 4096,
    "environment": {
      "OPENROUTER_API_KEY": "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"
    },
    "skills": ["service-requirement-analysis", "provider-certification-verification", "service-order-generation", "timeline-scheduling"]
  }'::jsonb,
  NOW(),
  NOW()
FROM companies c
WHERE c.name = 'MeasureForge AI'
  AND NOT EXISTS (
    SELECT 1 FROM agents a
    WHERE a.name = 'Service Sage'
      AND a.company_id = c.id
  );

-- 5. Task Titan - Work Order Procurement Agent
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  runtime_config,
  adapter_config,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  c.id,
  'Task Titan',
  'specialist',
  'Work Order Procurement Agent - Builder',
  '💪',
  'active',
  (SELECT id FROM agents WHERE name = 'measureforge-ai-procurement-director' AND company_id = c.id),
  '["work-order-scope-definition", "labor-resource-allocation", "equipment-scheduling", "productivity-tracking"]',
  'hermes_local',
  '{"run_heartbeat": 300}'::jsonb,
  '{
    "adapter": "hermes_local",
    "model": "anthropic/claude-sonnet-4.5",
    "temperature": 0.7,
    "max_tokens": 4096,
    "environment": {
      "OPENROUTER_API_KEY": "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"
    },
    "skills": ["work-order-scope-definition", "labor-resource-allocation", "equipment-scheduling", "productivity-tracking"]
  }'::jsonb,
  NOW(),
  NOW()
FROM companies c
WHERE c.name = 'MeasureForge AI'
  AND NOT EXISTS (
    SELECT 1 FROM agents a
    WHERE a.name = 'Task Titan'
      AND a.company_id = c.id
  );

-- 6. Match Maker - Supplier Matching Agent
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  runtime_config,
  adapter_config,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  c.id,
  'Match Maker',
  'specialist',
  'Supplier Matching Agent - Builder',
  '💕',
  'active',
  (SELECT id FROM agents WHERE name = 'measureforge-ai-procurement-director' AND company_id = c.id),
  '["supplier-capability-analysis", "compliance-scoring", "geographic-coverage-mapping", "delivery-capability-assessment", "bbbee-verification"]',
  'hermes_local',
  '{"run_heartbeat": 300}'::jsonb,
  '{
    "adapter": "hermes_local",
    "model": "anthropic/claude-opus-4.6",
    "temperature": 0.7,
    "max_tokens": 4096,
    "environment": {
      "OPENROUTER_API_KEY": "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"
    },
    "skills": ["supplier-capability-analysis", "compliance-scoring", "geographic-coverage-mapping", "delivery-capability-assessment", "bbbee-verification"]
  }'::jsonb,
  NOW(),
  NOW()
FROM companies c
WHERE c.name = 'MeasureForge AI'
  AND NOT EXISTS (
    SELECT 1 FROM agents a
    WHERE a.name = 'Match Maker'
      AND a.company_id = c.id
  );

-- 7. Candy Connector - Candy Integration Agent
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  runtime_config,
  adapter_config,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  c.id,
  'Candy Connector',
  'specialist',
  'Candy Integration Agent - Builder',
  '🍬',
  'active',
  (SELECT id FROM agents WHERE name = 'measureforge-ai-integration-director' AND company_id = c.id),
  '["candy-api-integration", "material-category-mapping", "order-submission", "status-tracking"]',
  'hermes_local',
  '{"run_heartbeat": 300}'::jsonb,
  '{
    "adapter": "hermes_local",
    "model": "anthropic/claude-sonnet-4.5",
    "temperature": 0.7,
    "max_tokens": 4096,
    "environment": {
      "OPENROUTER_API_KEY": "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"
    },
    "skills": ["candy-api-integration", "material-category-mapping", "order-submission", "status-tracking"]
  }'::jsonb,
  NOW(),
  NOW()
FROM companies c
WHERE c.name = 'MeasureForge AI'
  AND NOT EXISTS (
    SELECT 1 FROM agents a
    WHERE a.name = 'Candy Connector'
      AND a.company_id = c.id
  );

-- 8. Budget Guardian - Budget Monitoring Agent
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  runtime_config,
  adapter_config,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  c.id,
  'Budget Guardian',
  'specialist',
  'Budget Monitoring Agent - Builder',
  '🛡️',
  'active',
  (SELECT id FROM agents WHERE name = 'measureforge-ai-finance-director' AND company_id = c.id),
  '["budget-tracking", "variance-analysis", "alert-generation", "trend-analysis", "cost-optimization"]',
  'hermes_local',
  '{"run_heartbeat": 300}'::jsonb,
  '{
    "adapter": "hermes_local",
    "model": "anthropic/claude-sonnet-4.5",
    "temperature": 0.7,
    "max_tokens": 4096,
    "environment": {
      "OPENROUTER_API_KEY": "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"
    },
    "skills": ["budget-tracking", "variance-analysis", "alert-generation", "trend-analysis", "cost-optimization"]
  }'::jsonb,
  NOW(),
  NOW()
FROM companies c
WHERE c.name = 'MeasureForge AI'
  AND NOT EXISTS (
    SELECT 1 FROM agents a
    WHERE a.name = 'Budget Guardian'
      AND a.company_id = c.id
  );

-- 9. Gate Keeper - Approval Routing Agent
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  runtime_config,
  adapter_config,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  c.id,
  'Gate Keeper',
  'specialist',
  'Approval Routing Agent - Builder',
  '🚪',
  'active',
  (SELECT id FROM agents WHERE name = 'measureforge-ai-operations-director' AND company_id = c.id),
  '["proc-order-integration", "approval-matrix-configuration", "escalation-handling", "notification-management"]',
  'hermes_local',
  '{"run_heartbeat": 300}'::jsonb,
  '{
    "adapter": "hermes_local",
    "model": "anthropic/claude-sonnet-4.5",
    "temperature": 0.7,
    "max_tokens": 4096,
    "environment": {
      "OPENROUTER_API_KEY": "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"
    },
    "skills": ["proc-order-integration", "approval-matrix-configuration", "escalation-handling", "notification-management"]
  }'::jsonb,
  NOW(),
  NOW()
FROM companies c
WHERE c.name = 'MeasureForge AI'
  AND NOT EXISTS (
    SELECT 1 FROM agents a
    WHERE a.name = 'Gate Keeper'
      AND a.company_id = c.id
  );

-- ============================================================
-- API KEY GENERATION FOR ALL AGENTS
-- ============================================================

-- Generate API keys for each agent (this would be done programmatically in production)
-- For now, we'll use placeholder keys that would be generated securely

INSERT INTO agent_api_keys (
  id,
  agent_id,
  company_id,
  name,
  api_key,
  key_hash,
  created_at
)
SELECT
  gen_random_uuid(),
  a.id,
  a.company_id,
  a.name || ' API Key',
  'PLACEHOLDER_KEY_SET_MANUALLY',
  encode(sha256(('pcak_' || gen_random_uuid()::text)::bytea), 'hex'),
  NOW()
FROM agents a
WHERE a.company_id = (SELECT id FROM companies WHERE name = 'MeasureForge AI')
  AND a.name IN ('Sage Weaver', 'Forge Master', 'Resource Baron', 'Service Sage', 'Task Titan', 'Match Maker', 'Candy Connector', 'Budget Guardian', 'Gate Keeper')
  AND NOT EXISTS (
    SELECT 1 FROM agent_api_keys ak WHERE ak.agent_id = a.id
  );

-- ============================================================
-- MODEL ASSIGNMENTS (if agent_models table exists)
-- Note: Based on schema inspection, this table may not exist in current schema
-- ============================================================

-- This section would create model assignments if the table exists
-- SELECT table_name FROM information_schema.tables WHERE table_name = 'agent_models';

-- ============================================================
-- ACTIVITY LOG ENTRIES
-- ============================================================

INSERT INTO activity_log (
  id,
  company_id,
  agent_id,
  action,
  details,
  created_at
)
SELECT
  gen_random_uuid(),
  a.company_id,
  a.id,
  'agent_created',
  jsonb_build_object(
    'agent_name', a.name,
    'agent_title', a.title,
    'created_by', 'Nimbus - Supabase Database Specialist',
    'purpose', 'Builder procurement segregation workflows'
  ),
  NOW()
FROM agents a
WHERE a.company_id = (SELECT id FROM companies WHERE name = 'MeasureForge AI')
  AND a.name IN ('Sage Weaver', 'Forge Master', 'Resource Baron', 'Service Sage', 'Task Titan', 'Match Maker', 'Candy Connector', 'Budget Guardian', 'Gate Keeper');

-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================

-- Count of created agents
-- SELECT COUNT(*) as agent_count FROM agents
-- WHERE company_id = (SELECT id FROM companies WHERE name = 'MeasureForge AI')
--   AND name IN ('Sage Weaver', 'Forge Master', 'Resource Baron', 'Service Sage', 'Task Titan', 'Match Maker', 'Candy Connector', 'Budget Guardian', 'Gate Keeper');

-- List all created agents with details
-- SELECT a.name, a.title, a.status, a.reports_to, a.adapter_config->>'model' as model
-- FROM agents a
-- WHERE a.company_id = (SELECT id FROM companies WHERE name = 'MeasureForge AI')
--   AND a.name IN ('Sage Weaver', 'Forge Master', 'Resource Baron', 'Service Sage', 'Task Titan', 'Match Maker', 'Candy Connector', 'Budget Guardian', 'Gate Keeper')
-- ORDER BY a.name;

-- API key verification
-- SELECT a.name, COUNT(ak.id) as api_keys
-- FROM agents a
-- LEFT JOIN agent_api_keys ak ON a.id = ak.agent_id
-- WHERE a.company_id = (SELECT id FROM companies WHERE name = 'MeasureForge AI')
--   AND a.name IN ('Sage Weaver', 'Forge Master', 'Resource Baron', 'Service Sage', 'Task Titan', 'Match Maker', 'Candy Connector', 'Budget Guardian', 'Gate Keeper')
-- GROUP BY a.name
-- ORDER BY a.name;

-- Activity log verification
-- SELECT a.name, al.action, al.details->>'purpose' as purpose, al.created_at
-- FROM agents a
-- JOIN activity_log al ON a.id = al.agent_id
-- WHERE a.company_id = (SELECT id FROM companies WHERE name = 'MeasureForge AI')
--   AND a.name IN ('Sage Weaver', 'Forge Master', 'Resource Baron', 'Service Sage', 'Task Titan', 'Match Maker', 'Candy Connector', 'Budget Guardian', 'Gate Keeper')
--   AND al.action = 'agent_created'
-- ORDER BY a.name;