-- ============================================================
-- DELETE ALL ISSUES - FK-SAFE DELETION SCRIPT
-- Generated by: Database Druid (paperclipforge-ai-databasedruid)
-- Generated on: 2026-04-28
-- Purpose: Delete all issues and related child records from the database
-- 
-- IMPORTANT: This script follows the SQL Generation Procedure
-- Reference: /docs-paperclip/procedures/database/sql-generation-procedure.md
-- Schema: /docs-paperclip/schema/issues-schema.md
-- FK Map: /docs-paperclip/schema/FK table relationships.csv
-- ============================================================

-- ============================================================
-- PRE-EXECUTION CHECKLIST
-- [ ] Database backup completed
-- [ ] Reviewed FK dependencies (see Phase 1 below)
-- [ ] Confirmed this is the correct environment
-- [ ] Stakeholders notified of data deletion
-- ============================================================

BEGIN;

-- ============================================================
-- PHASE 1: SET NULL FOR NULLABLE FK REFERENCES TO ISSUES
-- These tables have nullable FKs that reference issues
-- Setting them to NULL prevents FK constraint violations
-- ============================================================

-- Update heartbeat_runs references (SET NULL on delete)
UPDATE document_revisions 
SET created_by_run_id = NULL 
WHERE created_by_run_id IN (
    SELECT hr.id FROM heartbeat_runs hr
    JOIN issues i ON hr.id = i.checkout_run_id OR hr.id = i.execution_run_id
);

UPDATE issue_comments 
SET created_by_run_id = NULL 
WHERE created_by_run_id IN (
    SELECT hr.id FROM heartbeat_runs hr
    JOIN issues i ON hr.id = i.checkout_run_id OR hr.id = i.execution_run_id
);

UPDATE issue_execution_decisions 
SET created_by_run_id = NULL 
WHERE created_by_run_id IN (
    SELECT hr.id FROM heartbeat_runs hr
    JOIN issues i ON hr.id = i.checkout_run_id OR hr.id = i.execution_run_id
);

UPDATE issue_thread_interactions 
SET source_run_id = NULL 
WHERE source_run_id IN (
    SELECT hr.id FROM heartbeat_runs hr
    JOIN issues i ON hr.id = i.checkout_run_id OR hr.id = i.execution_run_id
);

UPDATE issue_work_products 
SET created_by_run_id = NULL 
WHERE created_by_run_id IN (
    SELECT hr.id FROM heartbeat_runs hr
    JOIN issues i ON hr.id = i.checkout_run_id OR hr.id = i.execution_run_id
);

UPDATE workspace_operations 
SET heartbeat_run_id = NULL 
WHERE heartbeat_run_id IN (
    SELECT hr.id FROM heartbeat_runs hr
    JOIN issues i ON hr.id = i.checkout_run_id OR hr.id = i.execution_run_id
);

UPDATE workspace_runtime_services 
SET started_by_run_id = NULL 
WHERE started_by_run_id IN (
    SELECT hr.id FROM heartbeat_runs hr
    JOIN issues i ON hr.id = i.checkout_run_id OR hr.id = i.execution_run_id
);

-- Update execution_workspaces that reference issues (SET NULL)
UPDATE execution_workspaces 
SET source_issue_id = NULL 
WHERE source_issue_id IN (SELECT id FROM issues);

-- Update workspace_runtime_services that reference issues (SET NULL)
UPDATE workspace_runtime_services 
SET issue_id = NULL 
WHERE issue_id IN (SELECT id FROM issues);

-- Update routine_runs that reference issues (SET NULL)
UPDATE routine_runs 
SET linked_issue_id = NULL 
WHERE linked_issue_id IN (SELECT id FROM issues);

-- Update routines that reference issues as parent (SET NULL)
UPDATE routines 
SET parent_issue_id = NULL 
WHERE parent_issue_id IN (SELECT id FROM issues);

-- ============================================================
-- PHASE 2: DELETE CHILD RECORDS (CASCADE DELETES)
-- These tables have CASCADE delete rules or must be explicitly deleted
-- Ordered from deepest dependencies to shallowest
-- ============================================================

-- Delete cost_events referencing issues (NO ACTION - explicit delete required)
DELETE FROM cost_events 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete finance_events referencing issues (NO ACTION - explicit delete required)
DELETE FROM finance_events 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete feedback_votes referencing issues (NO ACTION - explicit delete required)
DELETE FROM feedback_votes 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete feedback_exports referencing issues (CASCADE - but explicit for clarity)
DELETE FROM feedback_exports 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete issue_approvals (CASCADE on delete)
DELETE FROM issue_approvals 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete issue_attachments (CASCADE on delete)
DELETE FROM issue_attachments 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete issue_comments (NO ACTION - explicit delete required)
DELETE FROM issue_comments 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete issue_documents (CASCADE on delete)
DELETE FROM issue_documents 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete issue_execution_decisions (CASCADE on delete)
DELETE FROM issue_execution_decisions 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete issue_inbox_archives (NO ACTION - explicit delete required)
DELETE FROM issue_inbox_archives 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete issue_labels (CASCADE on delete)
DELETE FROM issue_labels 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete issue_read_states (NO ACTION - explicit delete required)
DELETE FROM issue_read_states 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete issue_reference_mentions (CASCADE on delete for both source and target)
DELETE FROM issue_reference_mentions 
WHERE source_issue_id IN (SELECT id FROM issues) 
   OR target_issue_id IN (SELECT id FROM issues);

-- Delete issue_relations (CASCADE on delete for both issue_id and related_issue_id)
DELETE FROM issue_relations 
WHERE issue_id IN (SELECT id FROM issues) 
   OR related_issue_id IN (SELECT id FROM issues);

-- Delete issue_thread_interactions (NO ACTION - explicit delete required)
DELETE FROM issue_thread_interactions 
WHERE issue_id IN (SELECT id FROM issues);

-- Delete issue_work_products (CASCADE on delete)
DELETE FROM issue_work_products 
WHERE issue_id IN (SELECT id FROM issues);

-- ============================================================
-- PHASE 3: HANDLE SELF-REFERENCING FK (parent_id)
-- Issues can reference other issues as parents
-- Clear parent_id to break circular dependencies
-- ============================================================

UPDATE issues 
SET parent_id = NULL 
WHERE parent_id IS NOT NULL;

-- ============================================================
-- PHASE 4: DELETE ALL ISSUES
-- Now that all child records and circular references are handled,
-- we can safely delete all issues
-- ============================================================

DELETE FROM issues;

-- ============================================================
-- PHASE 5: VERIFICATION
-- Check that all issues have been deleted
-- ============================================================

DO $$
DECLARE
    remaining_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO remaining_count FROM issues;
    
    IF remaining_count > 0 THEN
        RAISE EXCEPTION 'Deletion incomplete: % issues remain', remaining_count;
    ELSE
        RAISE NOTICE 'SUCCESS: All issues deleted successfully';
    END IF;
END $$;

COMMIT;

-- ============================================================
-- POST-EXECUTION SUMMARY
-- 
-- Tables affected (in deletion order):
-- 1. SET NULL operations (11 tables):
--    - document_revisions, issue_comments, issue_execution_decisions
--    - issue_thread_interactions, issue_work_products
--    - workspace_operations, workspace_runtime_services
--    - execution_workspaces, routine_runs, routines
-- 
-- 2. DELETE operations (16 child tables):
--    - cost_events, finance_events, feedback_votes, feedback_exports
--    - issue_approvals, issue_attachments, issue_comments
--    - issue_documents, issue_execution_decisions, issue_inbox_archives
--    - issue_labels, issue_read_states, issue_reference_mentions
--    - issue_relations, issue_thread_interactions, issue_work_products
-- 
-- 3. Self-reference handling:
--    - issues.parent_id set to NULL
-- 
-- 4. Final deletion:
--    - All records from issues table
-- 
-- ROLLBACK PROCEDURE:
-- If this script fails or needs to be reversed, restore from the
-- pre-execution database backup created before running this script.
-- 
-- ACTIVITY LOG:
-- This operation should be logged to activity_log for audit trail:
-- INSERT INTO activity_log (company_id, actor_type, actor_id, action, 
--   entity_type, details, created_at)
-- VALUES (
--   (SELECT id FROM companies WHERE name = 'PaperclipForge AI'),
--   'agent', 'paperclipforge-ai-databasedruid', 'bulk_delete',
--   'issue', '{"operation": "delete_all_issues", "timestamp": "2026-04-28"}'::jsonb,
--   NOW()
-- );
-- ============================================================
